title: SolCoder
description: AI Code Editor that Helps Solana Developers Build Faster
theme: jekyll-theme-midnight
show_downloads: false

# Custom variables
github_username: SolCoderApp
twitter_username: SolCoder_
